[2025-08-14T02:30:30.358+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data __airflow_temporary_run_2025-08-14T02:30:29.749605+00:00__ [queued]>
[2025-08-14T02:30:30.369+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data __airflow_temporary_run_2025-08-14T02:30:29.749605+00:00__ [queued]>
[2025-08-14T02:30:30.369+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-14T02:30:30.385+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-14 00:00:00+00:00
[2025-08-14T02:30:30.388+0000] {standard_task_runner.py:60} INFO - Started process 74860 to run task
[2025-08-14T02:30:30.391+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', '__***_temporary_run_2025-08-14T02:30:29.749605+00:00__', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpz0qdkvjg']
[2025-08-14T02:30:30.394+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask fetch_historical_data
[2025-08-14T02:30:30.413+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T02:30:30.456+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data __airflow_temporary_run_2025-08-14T02:30:29.749605+00:00__ [running]> on host 6ea13209f7fc
[2025-08-14T02:30:30.522+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='__***_temporary_run_2025-08-14T02:30:29.749605+00:00__'
[2025-08-14T02:30:30.527+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T02:30:30.529+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/batch_data_producer.py 2025-08-14']
[2025-08-14T02:30:30.544+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T02:30:33.145+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T02:30:33.192+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T02:30:33.199+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T02:30:33.201+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/__init__.py", line 26, in <module>
[2025-08-14T02:30:33.202+0000] {subprocess.py:93} INFO -     from .tickers import Tickers
[2025-08-14T02:30:33.202+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/tickers.py", line 26, in <module>
[2025-08-14T02:30:33.203+0000] {subprocess.py:93} INFO -     from . import Ticker, multi
[2025-08-14T02:30:33.204+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/multi.py", line 30, in <module>
[2025-08-14T02:30:33.205+0000] {subprocess.py:93} INFO -     import multitasking as _multitasking
[2025-08-14T02:30:33.207+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 36, in <module>
[2025-08-14T02:30:33.208+0000] {subprocess.py:93} INFO -     class PoolConfig(TypedDict):
[2025-08-14T02:30:33.209+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 44, in PoolConfig
[2025-08-14T02:30:33.212+0000] {subprocess.py:93} INFO -     engine: Union[type[Thread], type[Process]]  # Execution engine
[2025-08-14T02:30:33.213+0000] {subprocess.py:93} INFO - TypeError: 'type' object is not subscriptable
[2025-08-14T02:30:33.895+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T02:30:33.981+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T02:30:34.004+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250814T000000, start_date=20250814T023030, end_date=20250814T023033
[2025-08-14T02:30:34.029+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 35 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 74860)
[2025-08-14T02:30:34.083+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T02:30:34.130+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
